added logic to get players names and weapons and draw board
hugopassos/OOP---Milestone-1 pull request #2
Opened 2019-09-04 15:27 UTC by rtingchaleun

2019-09-04 23:06 UTC, JamesOkunlade requested changes
### Hello, devs!! 

I think you did a very good job as your code behaves as predicted.:slightly_smiling_face: However, just to ensure your code is clear and easy to manage I have recommended some of your processes to be grouped into methods. Please check my comments below to see them.

Although, there is no fixed/rigid way to achieve this project its important to group these processes into different methods rather than just writing long code so it will be easy to write tests for them.

Please improve on my comments as much as you can and request for one last re-review for this milestone. 

### Status: `Changes required`

Happy coding:sunglasses:

2019-09-04 23:06 UTC, JamesOkunlade commented on bin/main.rb
> +end
It would be better to have the whole getting player name and assigning weapon as a single method rather than just writing it like this. It will be important when you want to to write unit tests for these methods.

The method could be `player_data`. Get the name and probably automatically assign weapon `X` and `O` to the first and second player respectively. This is totally `optional` though.

2019-09-04 23:06 UTC, JamesOkunlade commented on bin/main.rb
> +active_weapon = player_one.weapon
A method `determine_player` or `player_turn` can be created as well that will be setting a variable `@player` to the current player. 

```
  def player_turn
      @player = @player1 ? @player1 : @player2
  end 
``` 
Occasionally the value of @player or @player will be reset to either `true` or `false` depending on if it's there turn. This particular style is `optional` as well. You can achieve it in however you deem fit but it is important to have it as a `method`.

2019-09-04 23:06 UTC, JamesOkunlade commented on bin/main.rb
> +
Rather than having players' inputs to be in the format `00`, `01`, `02` `...`, you should create a method `play` for placing a weapon in the grids and make each grid correspond to numbers ranging from `1...9`.

2019-09-05 17:28 UTC, maelfosso requested changes
Hello coders :smile: 

Thank you very much for the changes you did.
Just one more step to move forward: **Rewrite without the global variables**.

Using the **Global variables** in your code prevent you to separate logic from user interface. Also, as you are using global variables, you will reuse them somewhere else in your project, another class or file. In conclusion, it prevents you to guarantee the independence between parts of your project which one of the objective of OOP.

Kindly make the change and re-submit a new code review request.
Thanks.

2019-09-05 17:28 UTC, maelfosso commented on bin/main.rb
> +  $player_one = Player.new(name, weapon)
**`REQUIRED`**
Please, why are you using **global variables** ?
Sorry but you're not allowed to use it.

2019-09-05 22:11 UTC, Oghenebrume50 approved these changes
This looks good team :+1:, this milestone is approved

2019-09-05 22:27 UTC, merged